### ISSUE TITLE
Adding multiple endpoints to .graphqlconfig.yml breaks autocomplete and goto definition

### ISSUE THREAD

**Issue by FabHof** [graphql/vscode-graphql#101]
## Actual Behavior

When adding multiple endpoints to the .graphqlconfig.yml, this extension will not work

#### working .graphqlconfig.yml
```YAML
projects:
  ember-adam-oom:
    schemaPath: "app/schema.graphql
    includes: ["**/*.graphql"]
    excludes: ["node_modules"]
    extensions:
      endpoints:
        default: http://localhost:3001/graphql
```

####  not working .graphqlconfig.yml
```YAML
projects:
  ember-adam-oom:
    schemaPath: "app/schema.graphql
    includes: ["**/*.graphql"]
    excludes: ["node_modules"]
    extensions:
      endpoints:
        default: http://localhost:3001/graphql
        develop: https://some-dev-endpont/graphql
```

## Expected Behavior

autocomplete and goto definition should work independent of endpoints.

## Specifications

  - GraphQL for VSCode Extension Version: 0.1.7
  - VSCode Version: 1.31.1
  - OS Name: Windows 10 x64
  - OS Version: 1703 (Build 15063.1631)

**Comment by acao** [comment]
@FabHof sorry for this issue, I've confirmed that this is working in the latest release, although you'll have to manually specify

```yml
extensions:
	endpoints:
		default:
			url: "http://localhost:3001/graphql
		develop:
			url: "https://some-dev-endpont/graphql"
```
in graphql-config@3, the endpoints extension seems to be simplified as such, though i've considered just @ts-ignore'ing the new ts definitions to support the simpler config pattern used by many.

you can now use commonjs and process.env if you want, in case that's helpful
