### ISSUE TITLE
No code completion for graphql tag template, although execute query works

### ISSUE THREAD

**Issue by iangregsondev** [graphql/vscode-graphql#145]
## Actual Behavior

I have the following but no code completion is listed

```
const IndexPage = () => {
  const { site } = useStaticQuery(
    graphql`
      query TestMe {
        site {
          siteMetadata {
            title
            description
            author
          }
        }
      }
    `
  )
```

I am in gatsby.

My schema is created correctly as far as I can see

this is my files .graphqlconfig.yml

```
projects:
  blog:
    schemaPath: "schema.graphql"
    extensions:
      endpoints:
        default: "http://localhost:3000/___graphql"

```

I exported my schema using graph-cli get schema..

Clicking on the "execute query" does work.

![image](https://user-images.githubusercontent.com/2370364/71645558-74a9d000-2cda-11ea-8cd7-5b621348b381.png)

## Expected Behavior

To be able to get code completion inside of the graphql template literal.

Any ideas what I could be doing wrong, I think i have followed the docs as I should.

**Comment by doomsower** [comment]
Same for me. Here's my config:
```yaml
schema: ./services/backend/schema.graphql
documents: './services/admin/**/*.{ts,tsx}'
extensions:
  endpoints:
    default: http://localhost:3333/graphql
```

I've switched typescript version to workspace, installed `@divyenduz/ts-graphql-plugin` and added it to `tsconfig.json`, but it didn't help.

**Comment by benvp** [comment]
Has the same issue and have been struggling on this a bit. Your config looks not quite correct. As in the documentation, the config should be a `.graphqlconfig.yml` which is in your project root.
My config looks like this:

This will use an introspection file for the schema and match graphql, gql, ts and tsx files.
```
schemaPath: "src/graphql/__generated__/schema.json"
includes: ["**/*.{graphql,gql,ts,tsx}"]
```

Also I installed `@divyenduz/ts-graphql-plugin` and added it to the tsconfig.json plugin section. After switching the VSCode TypeScript Version to the workspace version it started to work. Notice that you need to restart VSCode after that to make the language service plugin reload.

**Comment by dleavitt** [comment]
for the next person who finds this, what specifically fixed it for me was:
- Using `schemaPath` as the keyname rather than `schema`
- Pointing `schemaPath` to json introspection query results, rather than the .gql schema itself

**Comment by doomsower** [comment]
Could someone post full config?

I've dumped introspection result into `./services/backend/schema.json` json, which looks like:

```json
{
  "data": {
    "__schema": {
      "queryType": {
        "name": "Query"
      },
      "mutationType": {
        "name": "Mutation"
      },
      "subscriptionType": null,
      "types": [...],
      "directives": [...]
    }
  }
}

```

In workspace root, `.graphqlconfig.yml` file looks like:

```yaml
schemaPath: 'services/backend/schema.json'
includes: ['**/*.{graphql,gql,ts,tsx}']
```

Base `tsconfig.json` contains plugin and other tconfigs extend it:
```
"compilerOptions": {
    "plugins": [
      {
        "name": "@divyenduz/ts-graphql-plugin"
      }
    ]
  }
```

When I open `.ts` file with `gql` template, GRAPQHL plugin indicator shows up in VSCode bottom bar, but autocompletion still doesn't work

**Comment by qhoekman** [comment]
I've got it to work but I noticed the Intellisense only works for JavaScript and not TypeScript. You can test this out by switching the language from your TypeScript file in the right-bottom corner to JavaScript.

The GraphQL language output says:
```
Acquiring model 'intellisense-members' for javascript
Querying IntelliCode service for available models.
Cached model is up to date.

```

**Comment by robertherber** [comment]
Can't get the autocomplete to work either. Execute query works. Tried using "ts-graphql-plugin" and changing name to schemaPath to no avail. Haven't been able to find any errors in the logs either. Any ideas? Solutions or just where to look for the error would be highly appreciated! :)

**Comment by KurganskySergey** [comment]
Doesn't work for me either. Im using windows 10. watchman is installed and added to path
$ watchman --version
20200501.140444.0

config file looks like this:
.graphqlrc
```
schema: http://localhost:3000/graphql
documents: "src/**/*.gql"
```

**Comment by ghry5** [comment]
Having the same problem. It works fine with .gql, .graphql files aswell as gql/graphql tags in js files... but not in ts... Also tried the mentioned `@divyenduz/ts-graphql-plugin` and switching to workspace TS version + restart like @benvp without success.
```
    schemaPath: generated/schema.json
    includes: ["**/*.{graphql,gql,js,ts,tsx}"]
```
Any ideas?

**Comment by GillesWHC** [comment]
Same here, GraphQL is present in the status bar, but there's no autocompletion whatsoever. The 'Execute Query' button does show. My `graphqlconfig.` looks like this:

```
{
  "schemaPath": "schema.graphql"
}
```

I've got Watchman installed and the extension isn't throwing any errors.

**Comment by slaivyn** [comment]
Same here... It works for ".js" files but not ".tsx" ones.
I ended up using this TS language service plugin for autocomplete: https://github.com/Quramy/ts-graphql-plugin

**Comment by acao** [comment]
y'all! glad to tell you i've been working on this last week. by upgrading the LSP server, we are gonna get a lot of nice new features including support for ts, jsx and tsx. only issue is that emmet html completions are polluting jsx/tsx completion lists, so once i get that sort issue figured out, it should be great!

just as an example of what it will provide - you'll be able to right click a fragment used in a tsx file, and peek definition :open_mouth:

**Comment by KurganskySergey** [comment]
> y'all! glad to tell you i've been working on this last week. by upgrading the LSP server, we are gonna get a lot of nice new features including support for ts, jsx and tsx. only issue is that emmet html completions are polluting jsx/tsx completion lists, so once i get that sort issue figured out, it should be great!
> 
> just as an example of what it will provide - you'll be able to right click a fragment used in a tsx file, and peek definition 😮

If im not mistaken it would work without **watchman** which is great for windows users. Looking forward to it!

**Comment by acao** [comment]
indeed, one of the many important improvements, so y'all can expect a release by next week!

**Comment by acao** [comment]
https://github.com/prisma-labs/vscode-graphql/issues/181#issuecomment-672337523 here is a pre-release for testing, we will release to the prisma namespace once we've had enough people confirm the improvements are working and we don't have any major regressions!

**Comment by jgoux** [comment]
@acao Hello, I just tried the pre-release and I don't have aucompletion in my gql fragments in tsx files.

Here is my configuration :
```
schema: http://localhost:8080/v1/graphql
documents:
  - "./src/{components,pages}/**/*.tsx"
extensions:
  codegen:
    hooks:
      afterAllFileWrite:
        - yarn eslint --fix
    generates:
      ./src/generated/graphql/hooks.ts:
        documents: "./src/{components,pages}/**/*.tsx"
        plugins:
          - typescript
          - typescript-operations
          - typescript-urql
        config:
          scalars:
            timestamptz: string
            uuid: string
          namingConvention:
            transformUnderscore: true
          skipTypename: true
          withComponent: false
          withHooks: true
  endpoints:
    default: "http://localhost:8080/v1/graphql"
```
