### ISSUE TITLE
Language features not working with multi projects

### ISSUE THREAD

**Issue by manlao** [graphql/vscode-graphql#205]
## Actual Behavior
Will only correctly validate first project

## Expected Behavior
Validation should work for all projects

## Steps to Reproduce the Problem Or Description
.graphqlrc.yml
```
projects:
  A:
    schema: ./src/schemas/A.json
    documents: ./src/graphql/A/**/*.gql
  B:
    schema: ./src/schemas/B.json
    documents: ./src/graphql/B/**/*.gql
```

## Specifications

  - GraphQL for VSCode Extension Version: 0.3.1
  - VSCode Version: 1.48.2
  - OS Name: macOS
  - OS Version: 10.15.6

## Logs Of TS Server || GraphQL Language Service
Log shows it always validate file with project A
```
8/28/2020, 11:33:41 AM [4] (pid: 49707) graphql-language-service-usage-logs: {"type":"usage","messageType":"initialize"}

undefined
[Error - 11:33:51 AM] Request textDocument/documentSymbol failed.
  Message: Request textDocument/documentSymbol failed with message: A cached document cannot be found.
  Code: -32603 
8/28/2020, 11:33:51 AM [4] (pid: 49707) graphql-language-service-usage-logs: {"type":"usage","messageType":"textDocument/didOpen","projectName":"A","fileName":"file:///.../A/query.gql"}

undefined
8/28/2020, 11:33:57 AM [4] (pid: 49707) graphql-language-service-usage-logs: {"type":"usage","messageType":"textDocument/didClose","projectName":"A","fileName":"file:///.../A/query.gql"}

undefined
[Error - 11:33:58 AM] Request textDocument/documentSymbol failed.
  Message: Request textDocument/documentSymbol failed with message: A cached document cannot be found.
  Code: -32603 
8/28/2020, 11:33:58 AM [4] (pid: 49707) graphql-language-service-usage-logs: {"type":"usage","messageType":"textDocument/didOpen","projectName":"A","fileName":"file:///.../B/query.gql"}

undefined
8/28/2020, 11:37:17 AM [4] (pid: 49707) graphql-language-service-usage-logs: {"type":"usage","messageType":"textDocument/didClose","projectName":"A","fileName":"file:///.../B/query.gql"}

undefined
```

**Comment by maslianok** [comment]
I'm experiencing the same problem.

`.graphqlrc.json`

```
{
  "projects": {
    "github": {
      "schema": "src/generated/github-schema.graphql",
      "documents": ["src/**/*.github.gql"]
    },
    "hasura": {
      "schema": "src/generated/hasura-schema.graphql",
      "documents": ["src/**/*.hasura.gql"]
    }
  }
}
```

in my case, both queries get validated using the first schema

**Comment by acao** [comment]
thanks for reporting! must be an issue with how we upgraded graphql-config@3

**Comment by acao** [comment]
tracking the fix here: https://github.com/graphql/graphiql/issues/1655

**Comment by acao** [comment]
@maslianok fixed now in latest release! there was a regression with the major version upgrade of graphql-config. tested it manually and extensively so. let me know if you have any other issues.

**Comment by Risbot** [comment]
I have absolutely the same issue in the version v0.3.10.  Only I do not know, if this bugfix is contained in the version v0.3.10

**Comment by Risbot** [comment]
Something news here? I have still this problem.

**Comment by acao** [comment]
might be graphql config issues? my company changed priorities so it could be a while before i can help. i will publish my example repo with the working multi-project config soon!

**Comment by Risbot** [comment]
here is my config file `.graphqlrc.yml` content: 

```
projects:
  project1:
    schema: ./packages/project1/graphql-api/schema.graphql
    documents: ./packages/project1/gqls/*.ts
  project2:
    schema: ./packages/project2/graphql/schema.gql
    documents: ./packages/project2/**/*.graphql
    exclude: ./packages/project2/**/*.test.(tsx|ts)
```

project1 is work correctly but project2 ignoring itself configuration.
When I change positions of projects,  project2 start working like  project1 before, and project1 have same issue like project2 before
