### ISSUE TITLE
File "glob" patterns don't work for `schema` config pointers

### ISSUE THREAD

**Issue by acao** [graphql/vscode-graphql#239]
## Actual Behavior
```yml
schema: "src/schema/**/*.ts"
extensions:
  languageService:
    useSchemaFileDefinitions: true
```
- does not point to schema files for definitions
- sometimes, definitions don't work

## Expected Behaviour

```yml
schema: "src/schema/**/*.ts"
extensions:
  languageService:
    useSchemaFileDefinitions: true
```

should lead to all files in `src/schema` loading with SDL definition entries

## Steps to Reproduce the Problem Or Description

```yml
schema: "src/schema/**/*.ts"
extensions:
  languageService:
    useSchemaFileDefinitions: true
```

## Specifications

  - GraphQL for VSCode Extension Version: 
  - VSCode Version:
  - OS Name:
  - OS Version:

## Fix

The fix involves using something like `fast-glob` to detect graphql config glob paths and parse and cache the files in our custom implementation. the implementation only needs to happen in one place, too!
