### ISSUE TITLE
Go to definition not working

### ISSUE THREAD

**Issue by ITSWYoo** [graphql/vscode-graphql#266]
## Actual Behavior
Go to definition to another schema file not working.
Go only to the definition in that file.
## Expected Behavior
Go to definition to another schema file

If I add documents, I can move to the definition of another file.
However, `Type "XXX" already exists in the schema. It cannot also be defined in this type definition.`
An error occurs.
```yml
schema: 'packages/server/graphql/schema/**/*.schema.gql'
exclude: 'packages/**/graphql/documents/**/*.gql'
documents: 'packages/server/graphql/schema/**/*.schema.gql'
extensions:
  customDirectives:
    - directive @client on FIELD
  languageService:
      useSchemaFileDefinitions: true
```
## Steps to Reproduce the Problem Or Description
```yml
# .graphqlrc.yml
schema: 'packages/server/graphql/schema/**/*.schema.gql'
exclude: 'packages/**/graphql/documents/**/*.gql'
extensions:
  customDirectives:
    - directive @client on FIELD
  languageService:
      useSchemaFileDefinitions: true
```

```
// vscode settings.json 
{
  "workbench.colorTheme": "One Dark Pro",
  "workbench.iconTheme": "vscode-icons",
  "window.zoomLevel": 0,
  "eslint.alwaysShowStatus": true,
  "terminal.integrated.shellArgs.osx": [],
  "files.associations": {
    "*.js": "javascriptreact"
  },
  "javascript.format.enable": false,
  "eslint.format.enable": true,
  "typescript.updateImportsOnFileMove.enabled": "always",
  "editor.suggestSelection": "first",
  "java.semanticHighlighting.enabled": true,
  "java.configuration.checkProjectSettingsExclusions": false,
  "editor.largeFileOptimizations": false,
  "javascript.updateImportsOnFileMove.enabled": "always",
  "editor.tabSize": 2,
  "json.maxItemsComputed": 20000,
  "editor.formatOnSave": true,
  "editor.codeActionsOnSave": {
    // For ESLint
    "source.fixAll.eslint": true
  },
  "[json]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "[jsonc]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "vscode-graphql.useSchemaFileDefinitions": true,
  "editor.fontLigatures": null
}

```
## Specifications
  - GraphQL for VSCode Extension Version: 0.3.13
  - VSCode Version:1.52.0
  - OS Name: macOS
  - OS Version: 10.15.4
