### ISSUE TITLE
Extension does not show autocomplete/annotations if gql  file is included in documents field

### ISSUE THREAD

**Issue by ChrisW-B** [graphql/vscode-graphql#288]
## Actual Behavior
If my `.graphqlrc` file looks like the following: 

```yaml
projects:
  projA:
    schema: ./schema/projA.generated.graphql
    include: '**/projA/**/*.gql'
    extensions:
      endpoints:
        default:
          url: ${PROJ_A_QUERY_URL}
  projB:
    schema: ./schema/projB.generated.graphql
    include: '**/*.gql'
    extensions:
      endpoints:
        default:
          url: ${PROJ_B_QUERY_URL}
```

I have full working annotations and autocomplete. However, this means that certain linting does not work with [https://github.com/dotansimha/graphql-eslint](GraphQL-ESLint), as some of those require the `documents` field be used rather than the include.

This same config
```yaml
projects:
  projA:
    schema: ./schema/projA.generated.graphql
    documents: '**/projA/**/*.gql'
    extensions:
      endpoints:
        default:
          url: ${PROJ_A_QUERY_URL}
  projB:
    schema: ./schema/projB.generated.graphql
    documents: '**/*.gql'
    extensions:
      endpoints:
        default:
          url: ${PROJ_A__QUERY_URL}
```
does not surface annotations. With debugging turned on, the only output from vscode-graphql is
```
Debugger listening on ws://localhost:6009/1957c500-62e2-4b13-aefa-99772de13fd1
Debugger listening on ws://localhost:6009/1957c500-62e2-4b13-aefa-99772de13fd1
For help, see: https://nodejs.org/en/docs/inspector
3/5/2021, 3:34:35 PM [4] (pid: 14457) graphql-language-service-usage-logs: {"type":"usage","messageType":"initialize"}
```
## Expected Behavior
Annotations and autocomplete should still work
## Steps to Reproduce the Problem Or Description
1. configure project with a schema similar to 
```yaml
schema: ./schema.graphql
documents: '**/*.gql'
extensions:
  endpoints:
    default:
      url: ${QUERY_URL}
```
2. Attempt to edit a `.gql` file
## Specifications

  - GraphQL for VSCode Extension Version: v0.3.15
  - VSCode Version: 1.55.0-insider
  - OS Name: MacOS 
  - OS Version: v11.2.2

## Logs Of TS Server || GraphQL Language Service
```
Debugger listening on ws://localhost:6009/1957c500-62e2-4b13-aefa-99772de13fd1
Debugger listening on ws://localhost:6009/1957c500-62e2-4b13-aefa-99772de13fd1
For help, see: https://nodejs.org/en/docs/inspector
3/5/2021, 3:34:35 PM [4] (pid: 14457) graphql-language-service-usage-logs: {"type":"usage","messageType":"initialize"}
```
