### ISSUE TITLE
Executing Query does not use headers

### ISSUE THREAD

**Issue by jmarbutt** [graphql/vscode-graphql#298]
## Actual Behavior
When defining schema in `.graphqlrc.yml` but no end points does not use the headers when executing queries from a query in vs code. 

## Expected Behavior
It should use the end point with the default schema headers

## Steps to Reproduce the Problem Or Description
This is using a docker hosted version of Hasura but any graph ql api should work.

1. Create a .graphqlrc.yml like the following:
```yml
schema: 
    - http://localhost:8080/v1/graphql:
        headers:
            X-Hasura-Admin-Secret: 123456
documents:
    - ./src/**/*.tsx
    - ./src/**/*.ts
    - ./src/**/*.graphql
overwrite: true
generates:
    ./src/graphql/graphql.ts:
        plugins:
            - typescript
            - typescript-operations
            - typescript-react-apollo
            - typescript-apollo-client-helpers
        config:
            skipTypename: false
            withHooks: true
    ./src/graphql/graphql.schema.graphql:
        plugins: 
            - schema-ast
```
2. Create a `.graphql` file with the a query, for example:
```graphql
 query getMyAccounts { 
     
        accounts(order_by: { name: asc }) {
            id,
            name
        }
    }
```
3. Click `Execute Query` in Visual studio 
![image](https://user-images.githubusercontent.com/1386587/116336409-1db4ed80-a79e-11eb-8e20-3171d6f57ba6.png)
4. Should run the query. 

## Specifications

  - GraphQL for VSCode Extension Version:  0.1.2
  - VSCode Version: 1.55.2
  - OS Name: Windows 10
  - OS Version: 

## Logs Of TS Server || GraphQL Language Service

The warning in the logs is:
```console
Warning: endpoints missing from graphql config. will try 'schema' value(s) instead
```

**Comment by emmiep** [comment]
@jmarbutt Have you tried using the endpoints extension as shown in [this example](https://github.com/graphql/vscode-graphql#advanced-example)?

I haven't tried using a yaml file for configuration, but I guess in your case it should look something like this:

```yaml
schema: http://localhost:8080/v1/graphql
extensions:
  endpoints:
    default:
      url: http://localhost:8080/v1/graphql
      headers:
        X-Hasura-Admin-Secret: 123456
```
