### ISSUE TITLE
queries always sent to the first project's graphql endpoint

### ISSUE THREAD

**Issue by waterdrop01** [graphql/vscode-graphql#316]
## Actual Behavior
Here is my `.graphqlrc.yml` config file:

```
projects:
  first:
    schema: ./first.graphql
    documents: ./src/first-gql.js
    extensions:
      endpoints:
        default:
          url: https://first
  second:
    schema: ./second.graphql
    documents: ./src/second-gql.js
    extensions:
      endpoints:
        default:
          url: https://second
```

When in the `./src/second-gql.js` file, and clicking on the "query" button, the request is sent to `https://first`.

  - GraphQL for VSCode Extension Version: 3.0.16
  - VSCode Version: 1.58
  - OS Name: Ubuntu
  - OS Version: 20.04

## Expected Behavior
Depending on the file? the query should be routed to the correct endpoint

## Logs Of TS Server || GraphQL Language Service
```
NetworkHelper: operation: query
NetworkHelper: endpoint: https://first
```
