### ISSUE TITLE
Getting FetchError when running query

### ISSUE THREAD

**Issue by daniel-a-leon** [graphql/vscode-graphql#321]
Version 0.3.17 works for me so I reverted to that.

## Actual Behavior
In GraphQL Execution Result window getting error
FetchError: request to http://localhost:8081/api/graphql?profile failed, reason: write EPROTO 140519593723880:error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER:../../third_party/boringssl/src/ssl/tls_record.cc:242:

## Expected Behavior
Query to run without error.

## Steps to Reproduce the Problem Or Description
.graphqlrc.yml:
```
projects:
  app:
    extensions:
      endpoints:
        default:
          url: http://localhost:8081/api/graphql?profile
          headers:
            Authorization: ApiKey ***
```

Execute any query. Get error.

## Specifications

  - GraphQL for VSCode Extension Version: 0.3.18
  - VSCode Version: 1.59.1 (Universal)
  - OS Name: macOS Big Sur
  - OS Version: 11.5.2

## Logs Of TS Server || GraphQL Language Service
NetworkHelper: operation: query
NetworkHelper: endpoint: http://localhost:8081/api/graphql?profile
