### ISSUE TITLE
Auto complete and validation for multiple projects.

### ISSUE THREAD

**Issue by soumi-akira** [graphql/vscode-graphql#322]
I want to use multiple GraphQL endpoint on single project, but this extension seems load only one (first) project even if multiple project exists on `graphql.config.yml`.

Here's example, only 3 files on directory.
Open the directory with VSCode that installed this extension.

**graphql.config.yml**
```yml
projects:
  rickandmortyapi:
    schema: https://rickandmortyapi.com/graphql
  spaceX:
    schema: https://api.spacex.land/graphql/
```

**spacex.graphql**
```graphql
query getUsers {
  users {
    id
    name
  }
}

query getDragons {
  dragons {
    id
    name
  }
}
```

**rickandmorty.graphql**
```graphql
query getCaracters {
  characters {
    results {
      name
    }
  }
}

query getLocations {
  locations {
    results {
      name
    }
  }
}
```

In above case, `rickandmorty.graphql` is perfectly validated and auto completed but `spacex.graphql` throws validation error.

> Cannot query field "users" on type "Query"

Yes, I know it is difficult to find proper project for each `.graphql` file automatically. So is there any way to assign specific project to each `.graphql` file? Can I find some reference about this anywhere?

If there's no way so far, I want feature like this.

**spacex.graphql**
```graphql
#[[spaceX]]
query getUsers {
  users {
    id
    name
  }
}

query getDragons {
  dragons {
    id
    name
  }
}
```

**rickandmorty.graphql**
```graphql
#[[rickandmortyapi]]
query getCaracters {
  characters {
    results {
      name
    }
  }
}

query getLocations {
  locations {
    results {
      name
    }
  }
}
```

**Comment by soumi-akira** [comment]
Auto detection by annotation inside file is best but even it is good to select project manually by using command pallet I think.

like `ctrl or cmd` + `P` -> `>VSCode Graphql - Change Project`

**Comment by ferm10n** [comment]
I thought that setting `documents` inside the project config would help it determine the project to use for each file.
Something like this:
```yaml
projects:
  rickandmortyapi:
    schema: https://rickandmortyapi.com/graphql
    documents:
      - rickandmorty.graphql
  spaceX:
    schema: https://api.spacex.land/graphql/
    documents:
      - spacex.graphql
```

However, inspecting the `GraphQL Language Server` output panel shows that it seems to just pick the first project defined every time (`"projectName":"rickandmortyapi"`)
