### ISSUE TITLE
Extension not working with .json/.yml graphql config

### ISSUE THREAD

**Issue by divyenduz** [graphql/vscode-graphql#40]
Originally reported by @jhalborg [here](https://github.com/prismagraphql/vscode-graphql/issues/15#issuecomment-399919955), [here](https://github.com/prismagraphql/vscode-graphql/issues/21#issuecomment-399979074), and [here](https://github.com/prismagraphql/vscode-graphql/issues/21#issuecomment-400215248).

**Comment by divyenduz** [comment]
@jhalborg, your configuration has `includes` under `includes`

```
projects:
  app:
    schemaPath: ./schema.graphql
    includes: [
      "includes": ["**/*.{graphql,ts,tsx}"],
    ]
    extensions:
      endpoints:
        default: http://localhost:4000/graphql
        dev: http://localhost:4000/graphql
```

From your last comment on the other issue, can you please fix that and revert? Thanks.

**Comment by divyenduz** [comment]
Also, the `includes` should only concern with `graphql` files i.e. it should look like `["**/*.graphql"]`

**Comment by jhalborg** [comment]
Sorry, there was a lot of copy+pasting and reverting going on in the experimentation. 

I've just tried on the same project with 
```
projects:
  app:
    schemaPath: ./schema.graphql
    includes: ["**/*.graphql"]
    extensions:
      endpoints:
        default: http://localhost:4000/graphql
        dev: http://localhost:4000/graphql
```

Out of desperation, I also tried removing the file type from `.graphqlconfig`, and tried it with both `.json` (with a JSON config), `.yaml` and `.yml`, but no luck. I still get 

```
ZEBRA 1: undefined undefined
ZEBRA: GraphQLProjectConfig {
  config: 
   { schemaPath: './schema.graphql',
     includes: [ '**/*.graphql' ],
     extensions: { endpoints: [Object], codegen: [Object] } },
  configPath: '[PROJECT PATH]/.graphqlconfig.yaml',
  projectName: 'app' } [PROJECT PATH]/schema.graphql
```

**Comment by divyenduz** [comment]
@jhalborg : Can you please update to [0.0.10](https://marketplace.visualstudio.com/items?itemName=Prisma.vscode-graphql) and try again?

I validated in the project that you had emailed me. After updating the configuration to be same as the above comment, it works.

Thanks!

**Comment by jhalborg** [comment]
Hey @divyenduz -

Thanks for helping, however it still doesn't work for me. Same project, `.graphqlconfig.yaml` is:

```
projects:
  app:
    schemaPath: schema.graphql
    includes: ["**/*.graphql"]
    extensions:
      endpoints:
        default: http://localhost:4000/graphql
        dev: http://localhost:4000/graphql
      
      codegen:
        - generator: prisma-binding
          language: typescript
          target: ./schema.graphql
          output:
            binding: src/generated/prisma.ts
```

I've made a short video demonstrating the issue here: https://youtu.be/ZpeHPLwJ6oc 

Anything else I should try?
