### ISSUE TITLE
Remote schemas are not supported.

### ISSUE THREAD

**Issue by mmakarin** [graphql/vscode-graphql#409]
## Actual Behavior

This extension does not work with remote schemas in graphql-config. i.e. http://somedomain.com/schema.gql
graphql-config supports that.

## Expected Behavior
Extension should support remote schema fetching.

## Steps to Reproduce the Problem Or Description
{
  schema: "https://someurl/schema.gql",
}

## Specifications

  - GraphQL for VSCode Extension Version: 0.34.1
  - VSCode Version: 1.63.0
  - OS Name: MacOS
  - OS Version: 12.0.1
  - graphql config filename and format example:
 `{
  schema: "http://someurl.com/schema.gql",
}`

**Comment by acao** [comment]
Thanks for reporting! I will check it out soon

**Comment by tepene** [comment]
I am able to load schemas directly from a remote url. Here my example for Hasura:

`.graphqlrc.yaml`
```yaml
schema:
  - http://172.17.0.1:8080/v1/graphql:
      headers:
        x-hasura-admin-secret: "password"
```
