### ISSUE TITLE
TypeError: Cannot read property 'schemaPath' of undefined

### ISSUE THREAD

**Issue by tomitrescak** [graphql/vscode-graphql#54]
Hi,

I cannot make this run on Windows ;(
I am receiving this error:

```
(node:6500) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[Error - 14:13:40] Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: Cannot read property 'projectName' of undefined
  Code: -32603 
```

This is my .graphqlconfig.yml

```yml
projects:
  app:
    schemaPath: "src/data/yoga/schema.graphql"
    includes: ["src/**/*.graphql"]
    extensions:
      endpoints:
        default: "http://localhost:4000"
      codegen:
        - generator: prisma-binding
          language: typescript
          output: 
            binding: src/data/generated/api.ts
  prisma:
    schemaPath: "src/data/generated/prisma.graphql"
    includes: ["src/**/*.graphql"]
    extensions:
      prisma: src/data/prisma/prisma.yml
      codegen:
        - generator: prisma-binding
          language: typescript
          output: 
            binding: src/data/generated/prisma.ts
```

All Works well on MAC with this setup

**Comment by ntziolis** [comment]
Seeing the same issue

**Comment by divyenduz** [comment]
@ntziolis : Are you also running windows? I will pick this up shortly.

**Comment by ntziolis** [comment]
Yes I am. That said, I'm pretty sure think this was related to an old graphql version. Since I updated the graphql version locally as well as globally the error has dissapeared and im getting linting and auto completion for .graphql files but not yet in gql tags. See the gql tag issue as I provided a repository for reproduction.

@tomitrescak What version of graphql or graphql-cli do you have installed globally/locally?

**Comment by tomitrescak** [comment]
@ntziolis no love for me ;(
I have 2.16.5 for graphql-cli and latest graphql.

**Comment by tomitrescak** [comment]
@ntziolis @divyenduz do you maybe have a repo that I can download and test, whether the problem is not in my configuration? My error window is full of following:

```
(node:28068) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 12): TypeError: Cannot read property 'schemaPath' of undefined
[Error - 11:55:18] Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: Cannot read property 'projectName' of undefined
  Code: -32603 
[Error - 11:55:18] Request textDocument/definition failed.
  Message: Request textDocument/definition failed with message: Cannot read property 'configDir' of undefined
  Code: -32603 
```

**Comment by tomitrescak** [comment]
Sorry about one more message, my repo where it fails on windows but not on mac is here:

https://github.com/tomitrescak/corporator

**Comment by tomitrescak** [comment]
I have debugged the plugin and the issue seems to be in `GraphQLLanguageService.js` file.
The project config is not detected. In following lines, the `projectConfig` is not defined

```
projectConfig = this._graphQLConfig.getConfigForFile(uri);
schemaPath = projectConfig.schemaPath;
```

When I log the uri it comes a bit scrambled in the beginning.

```
file:///c%3A/Users/Tomi/Documents/Drive/Github/apps/corporator/src/data/prisma/localisation.graphql
```

**Comment by ntziolis** [comment]
@tomitrescak I actually did create a repo for exactly this purpose, see here: https://github.com/prismagraphql/vscode-graphql/issues/21#issuecomment-410504763

I'd be keen to know if this repo is working for you and if so which branch (local typescript version or vscode version)

**Comment by steebchen** [comment]
I have the same issue on Linux, so it seems that it's not necessarily windows specific. If you need more information please let me know.

**Comment by ntziolis** [comment]
@steebchen @tomitrescak  Can you guys clone the following super minimal repo and let us know if you still see the issue? This way we can eliminate miss configuration as a cause.

Note: I was seeing the same issue, but after setting up the configuration from scratch it went away. Hence I created this bare metal repo for testing.

**Comment by steebchen** [comment]
@ntziolis I don't have this error on your repo, instead I'm getting `Definition not found for GraphQL type String`. Autocompletion works in .graphql files, it does not in .ts gql template strings.

**Comment by bmfs** [comment]
I'm having the same issue in Mac

**Comment by tomitrescak** [comment]
@ntziolis I am wondering whether Go To definition works for you in .graphql files, when you are defining your schema. I tried several repos and no love for me.

prisma/1.15.1 (darwin-x64) node-v10.9.0

**Comment by dontsave** [comment]
Having this issue also on windows

**Comment by beeplin** [comment]
Same issue here. Windows 10 1709. And as @tomitrescak said above, Go To Definition does not work, either.

**Comment by ganemone** [comment]
It appears that the project key must be equal to the folder name in vscode. For example:

```js
{
  "projects": {
    "folder-name": { <---- this needs to be the folder you are working on
      "schemaPath": "generated/schema.graphql",
      "includes": ["src/graphql/**/*.graphql"],
      "extensions": {
        "endpoints": {
          "prod": "http://localhost:4000"
        }
      }
    }
  }
}
```

**Comment by chanlito** [comment]
Facing this issue as well using vscode on MacOS.

**Comment by cafrias** [comment]
Getting same error in Fedora 28.

`.graphqlconfig`:
```
{
  "projects": {
    "db": {
      "schemaPath": "prisma/datamodel.prisma",
      "includes": ["**/*.graphql"]
    }
  }
}
```

**Comment by dfreeman** [comment]
I've run into this on macOS as well, and found that the issue was a space in my project path.

The `configPath` on the `GraphQLConfig` object is a plain file path, but the path being passed into `getConfigForFile` is a `file:` URI that (crucially) is urlencoded, e.g. `' '` -> `'%20'`, and so no project matches.

**Comment by ph55** [comment]
Just installed plugin.
Same error

```
[Error - 6:19:54 PM] Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: Cannot read property 'projectName' of undefined
  Code: -32603
```

MacOS

**Comment by tomitrescak** [comment]
I never made this work. Using the Apollo version now. It does not have the go to definition for server defined schemas but otherwise works nicely.

**Comment by DarkEye123** [comment]
same here, tried all, nothing works.
my config.
`
{
  "projects": {
    "backend": {
      "schemaPath": "./src/schema.graphql",
      "includes": ["** /*.graphql"],
      "extensions": {
        "endpoints": {
          "default": "http://localhost:4444"
        }
      }
    },
    "prisma": {
      "schemaPath": "./src/generated/prisma.graphql",
      "includes": ["**/*.graphql"],
      "extensions": {
        "prisma": "prisma.yml"
      }
    }
  }
}
`
I noticed that 'schemaPath' thing occurs if prisma project is defined. If I remove it, it does not show  `UnhandledPromiseRejectionWarning` and `Request textDocument/hover failed.` but error

`Grammar is in an endless loop - Grammar is not advancing, nor is it pushing/popping` is still present

**Comment by 5achinJani** [comment]
Having the same issue in macOS.
`.graphqlconfig.yml`
```
projects:
  my-app:
    schemaPath: src/schema.graphql
    includes: ["**/*.graphql"]
    extensions:
      endpoints:
        default: http://localhost:4000
```

`my-app` is project folder name.
Extension version : 0.1.7
VScode version : 1.32.1
Node version : v10.0.0 using via nvm.
"graphql-yoga": "1.17.4",
schemaPath points at right place.
